name: YamatoPlugin
version: 1.2.2
main: lama.project.YamatoPlugin
api-version: '1.20.5'
author: Lama
website: https://github.com/ICEOF7/YamatoPlugin
description: Custom Yamato sword plugin for Spigot, Paper and Purpur.
commands:
  yamato:
    description: Yamato admin commands
    usage: /yamato give [player] | /yamato reload
    permission: yamato.admin
permissions:
  yamato.admin:
    default: op
